title: Open Science Community Nijmegen
description: A community for developing open science practices in Nijmegen.
permalink: /:title/
plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes
