# =====SITE SETTINGS=====
title: Open Science Community Nijmegen
description: A community for developing open science practices in Nijmegen.
permalink: /:title/
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

# =====DEFAULTS=====
# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# =====PLUGINS=====
plugins:
  - jekyll-remote-theme
